/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.placeholder.PlaceHolder;
import dao.UsuarioDao;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author RicardoSilvadeLima
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    PlaceHolder holder;
    public Login() {
        initComponents();
        holder = new PlaceHolder(usu, "Digite Seu Email");
        holder = new PlaceHolder(se, "Digite Sua Senha");
        JlCadastrar.setText("<html><u>Cadastrar</u>");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        usu = new javax.swing.JTextField();
        se = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        BtEntrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JlCadastrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(16, 24, 51));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(19, 46, 74));
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.setLayout(null);

        usu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        usu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuActionPerformed(evt);
            }
        });
        jPanel2.add(usu);
        usu.setBounds(50, 130, 320, 40);

        se.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seActionPerformed(evt);
            }
        });
        jPanel2.add(se);
        se.setBounds(50, 190, 320, 40);

        jLabel1.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 70, 90, 50);

        BtEntrar.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        BtEntrar.setForeground(new java.awt.Color(153, 153, 153));
        BtEntrar.setText("FAZER LOGIN AGORA");
        BtEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEntrarActionPerformed(evt);
            }
        });
        jPanel2.add(BtEntrar);
        BtEntrar.setBounds(50, 270, 320, 40);

        jLabel2.setText("Ele(a) AINDA NÃO possui uma Conta? Cadastre-o(a) Agora!!");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 330, 340, 14);

        JlCadastrar.setForeground(new java.awt.Color(102, 255, 255));
        JlCadastrar.setText("Cadastrar");
        jPanel2.add(JlCadastrar);
        JlCadastrar.setBounds(190, 340, 60, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(320, 40, 420, 430);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1010, 510);

        setSize(new java.awt.Dimension(1016, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuActionPerformed

    }//GEN-LAST:event_usuActionPerformed

    private void seActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seActionPerformed

    private void BtEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEntrarActionPerformed
        UsuarioDao dao = new UsuarioDao();
       
       if(dao.checkLogin(usu.getText(), se.getText())){
           new TelaPrincipal().setVisible(true);
           this.dispose();
       }else{
           JOptionPane.showMessageDialog(null, "Senha incorreta!");
       }


    }                                        

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {                                    
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
        }
    }//GEN-LAST:event_BtEntrarActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtEntrar;
    private javax.swing.JLabel JlCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField se;
    private javax.swing.JTextField usu;
    // End of variables declaration//GEN-END:variables
}
